### ISSUE TITLE
dot file upload readme?

### ISSUE THREAD

**Issue by Bombarding** [mketiku/dotfiles#1]
Hey, mind helping me out with this incase comp starts breaking?

**Comment by mketiku** [comment]
Sure, what's up?

**Comment by Bombarding** [comment]
I have been trying to find some upload tutorials but none are cut and dry. Would you mind giving me the terminal commands and process to set all this up, whats important etc. etc.

**Comment by Bombarding** [comment]
rip. found it thx ☢
